import { StyleSheet } from 'react-native';

import { AppThemeColors, Layout } from '@/constants/theme';

export function createHomeScreenStyles(theme: AppThemeColors) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      marginTop: Layout.sizes.safeAreaTop,
      backgroundColor: theme.background,
    },
    screen: {
      flex: 1,
      backgroundColor: theme.background,
    },
    scrollContent: {
      paddingBottom: Layout.spacing.xxl,
      backgroundColor: theme.background,
    },
    header: {
      gap: 14,
      paddingHorizontal: Layout.spacing.lg,
      paddingBottom: 18,
    },
    topBar: {
      position: 'relative',
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 32,
    },
    topBarTitle: {
      fontSize: 16,
      lineHeight: 20,
      color: theme.text,
    },
    topBarMenuButton: {
      width: 32,
      height: 32,
      borderRadius: Layout.radius.full,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.actionSurface,
      position: 'absolute',
      right: Layout.spacing.md,
    },
    menuSafeArea: {
      flex: 1,
    },
    menuBackdrop: {
      flex: 1,
      backgroundColor: theme.overlay,
    },
    menuSurface: {
      borderTopWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.card,
      overflow: 'hidden',
      shadowColor: '#000000',
      shadowOpacity: 0.16,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: 12 },
      elevation: 20,
    },
    menuSurfaceCompact: {
      width: '100%',
      marginTop: 'auto',
    },
    menuSurfaceWide: {
      width: 320,
      alignSelf: 'flex-end',
      marginTop: Layout.spacing.xxl,
    },
    menuHeader: {
      gap: Layout.spacing.xs,
      paddingHorizontal: Layout.spacing.lg,
      paddingTop: Layout.spacing.lg,
      paddingBottom: Layout.spacing.md,
    },
    menuActionList: {
      borderTopWidth: 1,
      borderTopColor: theme.border,
    },
    menuAction: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Layout.spacing.md,
      paddingHorizontal: Layout.spacing.lg,
      paddingVertical: Layout.spacing.md,
      backgroundColor: theme.card,
    },
    menuActionBorder: {
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    menuActionPressed: {
      opacity: 0.84,
    },
    menuActionIcon: {
      width: 34,
      height: 34,
      borderRadius: Layout.radius.full,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.actionSurface,
    },
    menuActionIconDanger: {
      backgroundColor: theme.highlightSurface,
    },
    menuActionLabel: {
      flex: 1,
      fontSize: 15,
      lineHeight: 20,
      color: theme.text,
    },
    menuActionLabelDanger: {
      color: theme.destructive,
    },
    menuDismissButton: {
      marginTop: Layout.spacing.sm,
      marginHorizontal: Layout.spacing.lg,
      marginBottom: Layout.spacing.lg,
      minHeight: 44,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.actionSurface,
    },
    menuDismissText: {
      fontSize: 14,
      lineHeight: 18,
      fontWeight: '700',
      color: theme.text,
    },
    identityRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
    },
    avatar: {
      width: Layout.sizes.avatarOuter,
      height: Layout.sizes.avatarOuter,
      borderRadius: Layout.sizes.avatarOuter / 2,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.avatarShell,
    },
    avatarInner: {
      width: Layout.sizes.avatarInner,
      height: Layout.sizes.avatarInner,
      borderRadius: Layout.sizes.avatarInner / 2,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.avatarFallback,
    },
    avatarImage: {
      width: Layout.sizes.avatarInner,
      height: Layout.sizes.avatarInner,
      borderRadius: Layout.sizes.avatarInner / 2,
    },
    statsRow: {
      alignSelf: 'center',
      flexDirection: 'row',
      flex: 1,
      justifyContent: 'space-evenly',
      paddingTop: Layout.spacing.md,
      marginLeft: Layout.spacing.lg,
    },
    statBlock: {
      alignItems: 'center',
      minWidth: 74,
    },
    statValue: {
      fontSize: 18,
      lineHeight: 22,
      fontWeight: '700',
      color: theme.text,
    },
    statLabel: {
      fontSize: 14,
      lineHeight: 18,
      color: theme.text,
    },
    identityCopy: {
      gap: Layout.spacing.xxs,
    },
    displayName: {
      fontSize: 13,
      lineHeight: 18,
      color: theme.text,
    },
    subtitle: {
      fontSize: 13,
      lineHeight: 18,
      color: theme.mutedText,
    },
    linkText: {
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '500',
      color: theme.accent,
    },
    sourceNote: {
      fontSize: 12,
      lineHeight: 16,
      marginTop: Layout.spacing.xs,
      color: theme.mutedText,
    },
    actionsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Layout.spacing.sm,
    },
    primaryButton: {
      flex: 1,
      minHeight: Layout.sizes.actionButtonHeight,
      borderRadius: Layout.radius.sm,
      paddingHorizontal: Layout.spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.accent,
    },
    primaryButtonText: {
      fontSize: 15,
      lineHeight: 20,
      fontWeight: '700',
      color: '#FFFFFF',
    },
    secondaryButton: {
      flex: 1,
      minHeight: Layout.sizes.actionButtonHeight,
      borderRadius: Layout.radius.sm,
      paddingHorizontal: Layout.spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.actionSurface,
    },
    highlightRow: {
      paddingTop: Layout.spacing.xxs,
      paddingBottom: Layout.spacing.xs,
      flexDirection: 'row',
    },
    highlightItem: {
      alignItems: 'center',
      width: Layout.sizes.highlightItemWidth,
      gap: 6,
    },
    highlightCircle: {
      width: Layout.sizes.highlight,
      height: Layout.sizes.highlight,
      borderRadius: Layout.radius.round,
      borderWidth: 1,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
      borderColor: theme.border,
      backgroundColor: theme.highlightSurface,
    },
    highlightImage: {
      width: '100%',
      height: '100%',
    },
    highlightLabel: {
      fontSize: 12,
      lineHeight: 16,
      maxWidth: Layout.sizes.highlightItemWidth,
      textAlign: 'center',
      color: theme.text,
    },
    tabBar: {
      flexDirection: 'row',
      borderTopWidth: 1,
      borderTopColor: theme.border,
      marginBottom: Layout.spacing.xxs,
    },
    tabItem: {
      flex: 1,
      height: Layout.sizes.tabHeight,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tabItemActive: {
      flex: 1,
      height: Layout.sizes.tabHeight,
      alignItems: 'center',
      justifyContent: 'center',
      borderTopWidth: 1,
      borderTopColor: theme.text,
    },
    emptyState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: Layout.spacing.md,
      paddingHorizontal: 36,
      paddingVertical: Layout.spacing.xl,
      backgroundColor: theme.background,
      borderColor: theme.border,
    },
    emptyIconCircle: {
      width: Layout.sizes.emptyCircle,
      height: Layout.sizes.emptyCircle,
      borderRadius: Layout.sizes.emptyCircle / 2,
      borderWidth: 1,
      borderColor: theme.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptyTitle: {
      textAlign: 'center',
      color: theme.text,
    },
    emptyAction: {
      paddingVertical: 6,
    },
    emptyActionText: {
      fontSize: 14,
      lineHeight: 18,
      fontWeight: '600',
      color: theme.accent,
    },
    listContent: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      margin: 'auto',
    },
    listProvider: {
      width: '100%',
    },
    listContainer: {
      width: '100%',
    },
    sortableItem: {
      borderRadius: 0,
    },
    tile: {
      flex: 1,
      borderRadius: 0,
      overflow: 'hidden',
      borderColor: theme.border,
      backgroundColor: theme.tileSurface,
    },
    lockedTile: {
      opacity: 0.94,
    },
    tileImage: {
      width: '100%',
      height: '100%',
    },
    tileOverlay: {
      ...StyleSheet.absoluteFillObject,
      padding: Layout.spacing.sm,
    },
    lockedBadge: {
      width: Layout.sizes.overlayButton,
      height: Layout.sizes.overlayButton,
      borderRadius: Layout.sizes.overlayButton / 2,
      marginLeft: 'auto',
      backgroundColor: theme.overlaySoft,
      alignItems: 'center',
      justifyContent: 'center',
    },
    removeButton: {
      width: Layout.sizes.overlayButton,
      height: Layout.sizes.overlayButton,
      borderRadius: Layout.sizes.overlayButton / 2,
      marginLeft: 'auto',
      backgroundColor: theme.overlay,
      alignItems: 'center',
      justifyContent: 'center',
    },
  });
}

export type HomeScreenStyles = ReturnType<typeof createHomeScreenStyles>;
